import fc from 'fast-check';
import { describe, it, expect } from 'vitest';
import {
  generateDaily,
  generateWeekly,
  generateOperatorMissions,
  _internal,
} from '@/app/lib/mastery/challenge-engine';
import { operators } from '@/app/data/operators';
import { CANONICAL_MULTIPLIERS } from '@/app/lib/mastery/xp-invariant';
import type { Challenge, ChallengeSlot, Objective, OperatorScope } from '@/app/types/mastery';

// --- Shared Arbitraries ---
// Use integer timestamps to avoid fc.date producing Date(NaN) during shrinking
const validDateArb = fc
  .integer({ min: new Date(2024, 0, 1).getTime(), max: new Date(2030, 0, 1).getTime() })
  .map((ts) => new Date(ts));

/**
 * Feature: operator-mastery-mvp, Property 2: Generated Challenge well-formedness
 *
 * Validates: Requirements 1.1, 1.2, 1.6, 1.8
 *
 * For any user, current local date, and slot, a Challenge generated by the
 * Challenge_Engine satisfies: slot ∈ {daily, weekly, mission}; target_count ∈
 * [1, 10] for daily, [5, 50] for weekly, [1, 50] for mission; objective is one
 * of the four valid objectives; operator_scope is one of the three valid scopes;
 * mastery_point_reward == target_count × 5; xp_override and xp_override_reason
 * are both null; and all required persisted fields are present.
 */
describe('Feature: operator-mastery-mvp, Property 2: Generated Challenge well-formedness', () => {
  const VALID_OBJECTIVES: Objective[] = [
    'complete_deployments',
    'win_rounds',
    'survive_rounds',
    'get_kills',
  ];
  const VALID_SCOPES: OperatorScope[] = ['any', 'random_pool', 'specific_operator'];
  const VALID_SLOTS: ChallengeSlot[] = ['daily', 'weekly', 'mission'];

  const userIdArb = fc.uuid();
  const operatorIdArb = fc.constantFrom(...operators.map((op) => op.id));

  it('generateDaily produces well-formed challenges with slot=daily and target_count in [1,10]', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, today) => {
        const result = generateDaily(userId, today);

        // Generation may fail (error case is tested in Property 5)
        if (result.challenge === null) return;

        const c = result.challenge;

        // Slot
        expect(c.slot).toBe('daily');
        expect(VALID_SLOTS).toContain(c.slot);

        // Target count range for daily: [1, 10]
        expect(c.targetCount).toBeGreaterThanOrEqual(1);
        expect(c.targetCount).toBeLessThanOrEqual(10);

        // Objective is valid
        expect(VALID_OBJECTIVES).toContain(c.objective);

        // Operator scope is valid
        expect(VALID_SCOPES).toContain(c.operatorScope);

        // Mastery point reward = target_count × 5
        expect(c.masteryPointReward).toBe(c.targetCount * 5);

        // XP overrides are null (generation never sets them)
        expect(c.xpOverride).toBeNull();
        expect(c.xpOverrideReason).toBeNull();

        // XP reward matches canonical formula
        expect(c.xpReward).toBe(c.targetCount * CANONICAL_MULTIPLIERS.daily);

        // All required fields are present
        expect(c.id).toBeDefined();
        expect(typeof c.id).toBe('string');
        expect(c.id.length).toBeGreaterThan(0);
        expect(c.slot).toBeDefined();
        expect(c.objective).toBeDefined();
        expect(c.targetCount).toBeDefined();
        expect(c.restriction).toBeDefined(); // can be null but must be present
        expect(c.operatorScope).toBeDefined();
        expect(c.operatorPool).toBeDefined();
        expect(Array.isArray(c.operatorPool)).toBe(true);
        expect(c.xpReward).toBeDefined();
        expect(c.masteryPointReward).toBeDefined();
        expect(c.generatedAt).toBeDefined();
        expect(typeof c.generatedAt).toBe('string');
        expect(c.progress).toBe(0);
        // role can be null but must be a key on the object
        expect('role' in c).toBe(true);
      }),
      { numRuns: 200 }
    );
  });

  it('generateWeekly produces well-formed challenges with slot=weekly and target_count in [5,50]', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, weekStart) => {
        const result = generateWeekly(userId, weekStart);

        if (result.challenge === null) return;

        const c = result.challenge;

        // Slot
        expect(c.slot).toBe('weekly');
        expect(VALID_SLOTS).toContain(c.slot);

        // Target count range for weekly: [5, 50]
        expect(c.targetCount).toBeGreaterThanOrEqual(5);
        expect(c.targetCount).toBeLessThanOrEqual(50);

        // Objective is valid
        expect(VALID_OBJECTIVES).toContain(c.objective);

        // Operator scope is valid
        expect(VALID_SCOPES).toContain(c.operatorScope);

        // Mastery point reward = target_count × 5
        expect(c.masteryPointReward).toBe(c.targetCount * 5);

        // XP overrides are null
        expect(c.xpOverride).toBeNull();
        expect(c.xpOverrideReason).toBeNull();

        // XP reward matches canonical formula
        expect(c.xpReward).toBe(c.targetCount * CANONICAL_MULTIPLIERS.weekly);

        // All required fields present
        expect(c.id).toBeDefined();
        expect(typeof c.id).toBe('string');
        expect(c.id.length).toBeGreaterThan(0);
        expect(c.slot).toBeDefined();
        expect(c.objective).toBeDefined();
        expect(c.targetCount).toBeDefined();
        expect(c.restriction).toBeDefined();
        expect(c.operatorScope).toBeDefined();
        expect(c.operatorPool).toBeDefined();
        expect(Array.isArray(c.operatorPool)).toBe(true);
        expect(c.xpReward).toBeDefined();
        expect(c.masteryPointReward).toBeDefined();
        expect(c.generatedAt).toBeDefined();
        expect(c.progress).toBe(0);
        expect('role' in c).toBe(true);
      }),
      { numRuns: 200 }
    );
  });

  it('generateOperatorMissions produces well-formed challenges with slot=mission and target_count in [1,50]', () => {
    fc.assert(
      fc.property(userIdArb, operatorIdArb, (userId, operatorId) => {
        const results = generateOperatorMissions(userId, operatorId);

        for (const result of results) {
          if (result.challenge === null) continue;

          const c = result.challenge;

          // Slot
          expect(c.slot).toBe('mission');
          expect(VALID_SLOTS).toContain(c.slot);

          // Target count range for mission: [1, 50]
          expect(c.targetCount).toBeGreaterThanOrEqual(1);
          expect(c.targetCount).toBeLessThanOrEqual(50);

          // Objective is valid
          expect(VALID_OBJECTIVES).toContain(c.objective);

          // Operator scope must be specific_operator for missions
          expect(c.operatorScope).toBe('specific_operator');

          // Mastery point reward = target_count × 5
          expect(c.masteryPointReward).toBe(c.targetCount * 5);

          // XP overrides are null
          expect(c.xpOverride).toBeNull();
          expect(c.xpOverrideReason).toBeNull();

          // XP reward matches canonical formula
          expect(c.xpReward).toBe(c.targetCount * CANONICAL_MULTIPLIERS.mission);

          // All required fields present
          expect(c.id).toBeDefined();
          expect(typeof c.id).toBe('string');
          expect(c.id.length).toBeGreaterThan(0);
          expect(c.slot).toBeDefined();
          expect(c.objective).toBeDefined();
          expect(c.targetCount).toBeDefined();
          expect(c.restriction).toBeDefined();
          expect(c.operatorScope).toBeDefined();
          expect(c.operatorPool).toBeDefined();
          expect(Array.isArray(c.operatorPool)).toBe(true);
          expect(c.xpReward).toBeDefined();
          expect(c.masteryPointReward).toBeDefined();
          expect(c.generatedAt).toBeDefined();
          expect(c.progress).toBe(0);
          expect('role' in c).toBe(true);
        }
      }),
      { numRuns: 200 }
    );
  });
});

/**
 * Feature: operator-mastery-mvp, Property 3: Random pool sizing and operator validity
 *
 * Validates: Requirements 1.3
 *
 * For any generated Challenge with operator_scope == 'random_pool', |operator_pool|
 * is in [1, 5] and every id in operator_pool exists in the operator catalog.
 * For any generated Challenge with operator_scope == 'specific_operator',
 * |operator_pool| equals 1 and the id exists in the operator catalog.
 * For any generated Challenge with operator_scope == 'any', operator_pool is empty.
 */
describe('Feature: operator-mastery-mvp, Property 3: Random pool sizing and operator validity', () => {
  const operatorIds = new Set(operators.map((op) => op.id));
  const userIdArb = fc.uuid();
  const operatorIdArb = fc.constantFrom(...operators.map((op) => op.id));

  /**
   * Helper to validate pool sizing for a generated challenge.
   */
  function assertPoolSizing(c: Challenge): void {
    switch (c.operatorScope) {
      case 'random_pool':
        expect(c.operatorPool.length).toBeGreaterThanOrEqual(1);
        expect(c.operatorPool.length).toBeLessThanOrEqual(5);
        // Every id in the pool must exist in the operator catalog
        for (const id of c.operatorPool) {
          expect(operatorIds.has(id)).toBe(true);
        }
        break;
      case 'specific_operator':
        expect(c.operatorPool.length).toBe(1);
        // The single id must exist in the operator catalog
        expect(operatorIds.has(c.operatorPool[0])).toBe(true);
        break;
      case 'any':
        expect(c.operatorPool.length).toBe(0);
        break;
    }
  }

  it('generateDaily: pool sizing respects operator_scope rules', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, today) => {
        const result = generateDaily(userId, today);
        if (result.challenge === null) return;
        assertPoolSizing(result.challenge);
      }),
      { numRuns: 200 }
    );
  });

  it('generateWeekly: pool sizing respects operator_scope rules', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, weekStart) => {
        const result = generateWeekly(userId, weekStart);
        if (result.challenge === null) return;
        assertPoolSizing(result.challenge);
      }),
      { numRuns: 200 }
    );
  });

  it('generateOperatorMissions: pool is exactly 1 valid operator for specific_operator scope', () => {
    fc.assert(
      fc.property(userIdArb, operatorIdArb, (userId, operatorId) => {
        const results = generateOperatorMissions(userId, operatorId);
        for (const result of results) {
          if (result.challenge === null) continue;
          assertPoolSizing(result.challenge);
          // Missions always have specific_operator scope
          expect(result.challenge.operatorScope).toBe('specific_operator');
          expect(result.challenge.operatorPool).toEqual([operatorId]);
        }
      }),
      { numRuns: 200 }
    );
  });
});

/**
 * Feature: operator-mastery-mvp, Property 4: Gadget restriction respects every operator in the pool
 *
 * Validates: Requirements 1.4
 *
 * For any generated Challenge with restriction.kind == 'gadget_only',
 * restriction.value appears in the gadgets list of every operator in operator_pool
 * (or, when operator_scope == 'any', in the gadgets list of every operator in the
 * operator catalog).
 */
describe('Feature: operator-mastery-mvp, Property 4: Gadget restriction respects every operator in the pool', () => {
  const userIdArb = fc.uuid();
  const operatorIdArb = fc.constantFrom(...operators.map((op) => op.id));

  function assertGadgetRestriction(c: Challenge): void {
    if (c.restriction === null || c.restriction.kind !== 'gadget_only') return;

    const gadgetValue = c.restriction.value;

    if (c.operatorScope === 'any') {
      // When scope is 'any', the gadget must exist in every operator in the catalog
      // Note: this is a very strict requirement. In practice, the engine may relax
      // this by dropping the restriction. If the challenge has gadget_only with 'any'
      // scope, it must hold for all operators in the catalog.
      for (const op of operators) {
        expect(op.gadgets).toContain(gadgetValue);
      }
    } else {
      // For random_pool or specific_operator, check against the pool
      for (const opId of c.operatorPool) {
        const op = operators.find((o) => o.id === opId);
        expect(op).toBeDefined();
        expect(op!.gadgets).toContain(gadgetValue);
      }
    }
  }

  it('generateDaily: gadget_only restriction value exists in gadgets of all pool operators', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, today) => {
        const result = generateDaily(userId, today);
        if (result.challenge === null) return;
        assertGadgetRestriction(result.challenge);
      }),
      { numRuns: 300 }
    );
  });

  it('generateWeekly: gadget_only restriction value exists in gadgets of all pool operators', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, weekStart) => {
        const result = generateWeekly(userId, weekStart);
        if (result.challenge === null) return;
        assertGadgetRestriction(result.challenge);
      }),
      { numRuns: 300 }
    );
  });

  it('generateOperatorMissions: gadget_only restriction value exists in the specific operator gadgets', () => {
    fc.assert(
      fc.property(userIdArb, operatorIdArb, (userId, operatorId) => {
        const results = generateOperatorMissions(userId, operatorId);
        for (const result of results) {
          if (result.challenge === null) continue;
          assertGadgetRestriction(result.challenge);
        }
      }),
      { numRuns: 300 }
    );
  });
});

/**
 * Feature: operator-mastery-mvp, Property 5: Constraint-relaxation retry
 *
 * Validates: Requirements 1.7
 *
 * The generation process retries at most 5 times with progressively relaxed
 * constraints. It either produces a valid challenge or surfaces an error
 * (never hangs or infinite loops).
 */
describe('Feature: operator-mastery-mvp, Property 5: Constraint-relaxation retry', () => {
  const userIdArb = fc.uuid();
  const operatorIdArb = fc.constantFrom(...operators.map((op) => op.id));

  it('generateDaily always terminates and returns either a valid challenge or an error', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, today) => {
        const result = generateDaily(userId, today);

        // Must return one of: valid challenge or error
        if (result.challenge !== null) {
          expect(result.error).toBeNull();
          // Valid challenge has non-empty id and correct slot
          expect(result.challenge.id.length).toBeGreaterThan(0);
          expect(result.challenge.slot).toBe('daily');
        } else {
          // Error case: challenge is null, error message is present
          expect(result.error).not.toBeNull();
          expect(typeof result.error).toBe('string');
          expect(result.error!.length).toBeGreaterThan(0);
        }
      }),
      { numRuns: 200 }
    );
  });

  it('generateWeekly always terminates and returns either a valid challenge or an error', () => {
    fc.assert(
      fc.property(userIdArb, validDateArb, (userId, weekStart) => {
        const result = generateWeekly(userId, weekStart);

        if (result.challenge !== null) {
          expect(result.error).toBeNull();
          expect(result.challenge.id.length).toBeGreaterThan(0);
          expect(result.challenge.slot).toBe('weekly');
        } else {
          expect(result.error).not.toBeNull();
          expect(typeof result.error).toBe('string');
          expect(result.error!.length).toBeGreaterThan(0);
        }
      }),
      { numRuns: 200 }
    );
  });

  it('generateOperatorMissions always terminates and returns either valid challenges or errors', () => {
    fc.assert(
      fc.property(userIdArb, operatorIdArb, (userId, operatorId) => {
        const results = generateOperatorMissions(userId, operatorId);

        // Should return an array (up to 3 results)
        expect(Array.isArray(results)).toBe(true);
        expect(results.length).toBeGreaterThanOrEqual(1);
        expect(results.length).toBeLessThanOrEqual(3);

        for (const result of results) {
          if (result.challenge !== null) {
            expect(result.error).toBeNull();
            expect(result.challenge.id.length).toBeGreaterThan(0);
            expect(result.challenge.slot).toBe('mission');
          } else {
            expect(result.error).not.toBeNull();
            expect(typeof result.error).toBe('string');
          }
        }
      }),
      { numRuns: 200 }
    );
  });

  it('internal generateChallenge respects MAX_RETRIES constant of 5', () => {
    // Verify the MAX_RETRIES constant is 5
    expect(_internal.MAX_RETRIES).toBe(5);
  });

  it('constraint relaxation drops restriction first, then role', () => {
    // Test the relaxConstraints function directly with impossible constraints
    const impossibleConstraints = {
      slot: 'daily' as ChallengeSlot,
      role: 'NonExistentRole_XYZ',
      objective: 'complete_deployments' as Objective,
      restriction: { kind: 'gadget_only' as const, value: 'NonExistentGadget_XYZ' },
      operatorScope: 'random_pool' as OperatorScope,
      targetCount: 5,
    };

    const relaxed = _internal.relaxConstraints(impossibleConstraints);

    // With a non-existent role AND non-existent gadget, relaxation should
    // eventually drop both. If it returns non-null, restriction and/or role
    // should be relaxed.
    if (relaxed !== null) {
      // If restriction was the problem, it should be null
      // If role was also the problem, it should also be null
      // The key invariant: the relaxed constraints produce a non-empty pool
      const pool = _internal.getEffectivePool(relaxed.role, relaxed.restriction);
      expect(pool.length).toBeGreaterThan(0);
    }
    // If relaxed is null, all relaxation attempts failed (which is valid)
  });

  it('relaxConstraints with valid role and no restriction returns original constraints', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(..._internal.ALL_ROLES),
        (role) => {
          const constraints = {
            slot: 'daily' as ChallengeSlot,
            role,
            objective: 'complete_deployments' as Objective,
            restriction: null,
            operatorScope: 'random_pool' as OperatorScope,
            targetCount: 5,
          };

          const pool = _internal.getEffectivePool(role, null);
          if (pool.length > 0) {
            const relaxed = _internal.relaxConstraints(constraints);
            expect(relaxed).not.toBeNull();
            // Should return original constraints since pool is non-empty
            expect(relaxed!.role).toBe(role);
            expect(relaxed!.restriction).toBeNull();
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});
